'use client'

export const dynamic = 'force-dynamic'

import Link from 'next/link'
import { useRouter } from 'next/navigation'

function S({ n, title }: { n: string; title: string }) {
  return (
    <h2 className="font-bold text-white text-lg mt-12 mb-4 pt-6 border-t"
      style={{ borderColor: 'rgba(255,255,255,0.07)' }}>
      {n}. {title}
    </h2>
  )
}

function Sub({ n, title }: { n: string; title: string }) {
  return (
    <h3 className="font-semibold mt-6 mb-2" style={{ color: 'rgba(255,255,255,0.85)', fontSize: 14 }}>
      {n} {title}
    </h3>
  )
}

function P({ children }: { children: React.ReactNode }) {
  return (
    <p className="text-sm leading-relaxed mb-3" style={{ color: 'rgba(255,255,255,0.62)' }}>
      {children}
    </p>
  )
}

function Li({ children }: { children: React.ReactNode }) {
  return (
    <li className="text-sm leading-relaxed" style={{ color: 'rgba(255,255,255,0.62)' }}>
      {children}
    </li>
  )
}

function InfoBox({ children }: { children: React.ReactNode }) {
  return (
    <div className="my-4 rounded-2xl border p-4"
      style={{ background: 'rgba(255,255,255,0.03)', borderColor: 'rgba(255,255,255,0.08)' }}>
      {children}
    </div>
  )
}

export default function PrivacyPage() {
  const router = useRouter()
  return (
    <div style={{ background: '#080808', minHeight: '100vh' }}>

      {/* Top bar */}
      <header className="sticky top-0 z-20 border-b flex items-center justify-between px-5 pb-3"
        style={{ background: 'rgba(8,8,8,0.92)', backdropFilter: 'blur(12px)', borderColor: 'rgba(255,255,255,0.07)', paddingTop: 'calc(env(safe-area-inset-top) + 12px)' }}>
        <button type="button" onClick={() => router.back()}
          className="flex items-center gap-1.5 text-sm font-medium"
          style={{ color: 'rgba(255,255,255,0.5)' }}>
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
            <polyline points="15 18 9 12 15 6" />
          </svg>
          Back
        </button>
        <span className="text-sm font-semibold text-white">Privacy Policy</span>
        <Link href="/terms" className="text-xs" style={{ color: 'rgba(255,255,255,0.4)' }}>
          Terms →
        </Link>
      </header>

      <main className="max-w-2xl mx-auto px-5 pb-36 pt-10">

        {/* Title block */}
        <div className="mb-10">
          <p className="text-xs font-semibold uppercase tracking-widest mb-3"
            style={{ color: 'rgba(255,255,255,0.3)' }}>
            Legal
          </p>
          <h1 className="font-bold text-white text-3xl mb-3">Privacy Policy</h1>
          <p className="text-sm" style={{ color: 'rgba(255,255,255,0.4)' }}>
            Effective Date: May 28, 2026 &nbsp;·&nbsp; Last Updated: May 28, 2026
          </p>
          <p className="text-sm mt-4 leading-relaxed" style={{ color: 'rgba(255,255,255,0.55)' }}>
            TripAlong (&quot;TripAlong,&quot; &quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) is committed to
            protecting your privacy. This Privacy Policy explains what information we collect, why we
            collect it, how we use and share it, and what rights you have. It applies to our mobile
            app, website at tripalong.app, and related services (collectively, the &quot;Service&quot;).
          </p>
          <p className="text-sm mt-3 leading-relaxed" style={{ color: 'rgba(255,255,255,0.55)' }}>
            By using the Service, you agree to the collection and use of information as described in
            this Policy. If you do not agree, do not use the Service.
          </p>
        </div>

        {/* ── 1 ── */}
        <S n="1" title="Information We Collect" />
        <P>We collect information you provide directly, information generated by your use of the Service, and information from third parties.</P>

        <Sub n="1.1" title="Account and Registration Information" />
        <InfoBox>
          <ul className="list-disc ml-4 space-y-1.5">
            <Li>Full name</Li>
            <Li>Email address</Li>
            <Li>Password (stored as an encrypted hash — we never store your plaintext password)</Li>
            <Li>Age</Li>
            <Li>Profile photo</Li>
            <Li>Sign-in method (email/password or Google OAuth)</Li>
          </ul>
        </InfoBox>

        <Sub n="1.2" title="Profile Information You Choose to Share" />
        <P>
          You control what you add to your public profile. This may include:
        </P>
        <InfoBox>
          <ul className="list-disc ml-4 space-y-1.5">
            <Li>Bio / about text</Li>
            <Li>City and country of residence</Li>
            <Li>Additional photos (photo grid)</Li>
            <Li>Travel DNA preferences: travel style, daily pace, social energy, planning style, experience level, travel-with preference</Li>
            <Li>Languages spoken, interests, countries visited, and bucket-list destinations</Li>
          </ul>
        </InfoBox>
        <P>
          Profile information (excluding private account details) is visible to other logged-in users
          of the Service as part of the core functionality of TripAlong.
        </P>

        <Sub n="1.3" title="Trip and Activity Data" />
        <InfoBox>
          <ul className="list-disc ml-4 space-y-1.5">
            <Li>Trips you create, including destination, dates, description, and cover image</Li>
            <Li>Trips you join or are invited to</Li>
            <Li>Trip membership information (who is in each trip group)</Li>
            <Li>Trip status and activity</Li>
          </ul>
        </InfoBox>

        <Sub n="1.4" title="Communications and Messages" />
        <P>
          We collect messages you send in group trip chats and direct messages (&quot;DMs&quot;) on the
          platform. Message content is stored on our servers to deliver it to recipients, to power
          features like message history, and to enable us to enforce our safety policies.
        </P>
        <P>
          <strong className="text-white">Please do not share highly sensitive personal information
          (financial details, government ID numbers, passwords) in messages.</strong>
        </P>

        <Sub n="1.5" title="Usage and Technical Data" />
        <P>When you use the Service, we automatically collect:</P>
        <InfoBox>
          <ul className="list-disc ml-4 space-y-1.5">
            <Li>Log data: IP address, device type, operating system, browser type, pages visited, features used, timestamps, error reports</Li>
            <Li>Device identifiers (e.g., device ID, advertising ID where applicable)</Li>
            <Li>App performance and crash report data</Li>
            <Li>Referring URLs and session duration</Li>
          </ul>
        </InfoBox>

        <Sub n="1.6" title="Information from Third-Party Sign-In (Google OAuth)" />
        <P>
          If you sign in with Google, we receive from Google the information you authorize Google to
          share, which typically includes your name, email address, and profile photo. We use this
          solely to create and authenticate your account. We do not receive your Google password.
        </P>

        {/* ── 2 ── */}
        <S n="2" title="How We Use Your Information" />
        <P>We use the information we collect to:</P>
        <ul className="list-disc ml-5 space-y-2 mb-4">
          <Li><strong className="text-white/80">Provide the Service:</strong> Create and manage your account, display your profile to other users, facilitate trip matching and group chats, and deliver messages</Li>
          <Li><strong className="text-white/80">Personalize your experience:</strong> Recommend trips, suggest compatible travel companions based on your Travel DNA, and customize your feed</Li>
          <Li><strong className="text-white/80">Communications:</strong> Send you notifications about messages, trip invites, and activity — with your permission via in-app settings</Li>
          <Li><strong className="text-white/80">Safety and trust:</strong> Detect, investigate, and prevent fraud, abuse, harassment, spam, and violations of our Terms of Service</Li>
          <Li><strong className="text-white/80">Customer support:</strong> Respond to your inquiries, reports, and requests</Li>
          <Li><strong className="text-white/80">Legal compliance:</strong> Comply with applicable laws, regulations, and legal process</Li>
          <Li><strong className="text-white/80">Service improvement:</strong> Analyze usage trends, fix bugs, conduct research, and develop new features</Li>
          <Li><strong className="text-white/80">Business operations:</strong> Manage our infrastructure, billing, and business processes</Li>
        </ul>

        {/* ── 3 ── */}
        <S n="3" title="How We Share Your Information" />

        <Sub n="3.1" title="With Other Users (Core Functionality)." />
        <P>
          TripAlong is a social platform. Sharing certain information with other users is necessary for
          the Service to function:
        </P>
        <ul className="list-disc ml-5 space-y-2 mb-4">
          <Li>Your <strong className="text-white/80">public profile</strong> (name, photos, bio, age, location, Travel DNA) is visible to all logged-in users browsing the feed or your profile</Li>
          <Li>Your <strong className="text-white/80">messages</strong> in a trip group chat are visible to all members of that group</Li>
          <Li>Your <strong className="text-white/80">direct messages</strong> are visible to the recipient</Li>
          <Li>Your <strong className="text-white/80">membership</strong> in a trip group is visible to other trip members</Li>
        </ul>
        <P>
          You can control the visibility of your profile by adjusting your privacy settings in the app.
          However, certain information (your name, profile photo) remains visible to trip members once
          you join a trip.
        </P>

        <Sub n="3.2" title="With Service Providers." />
        <P>
          We share information with trusted vendors and service providers who help us operate the
          Service:
        </P>
        <InfoBox>
          <ul className="list-disc ml-4 space-y-1.5">
            <Li><strong className="text-white/80">Supabase</strong> — database, authentication, and file storage (supabase.com/privacy)</Li>
            <Li><strong className="text-white/80">Google</strong> — sign-in authentication and analytics</Li>
            <Li><strong className="text-white/80">Vercel</strong> — web hosting and deployment</Li>
          </ul>
        </InfoBox>
        <P>
          These service providers are permitted to process your information only as necessary to provide
          their services to us and are bound by confidentiality obligations.
        </P>

        <Sub n="3.3" title="For Legal Compliance and Safety." />
        <P>
          We may disclose your information when we believe in good faith that disclosure is necessary to:
        </P>
        <ul className="list-disc ml-5 space-y-2 mb-4">
          <Li>Comply with applicable law, regulation, legal process, or governmental request (e.g., subpoena, court order)</Li>
          <Li>Protect the rights, property, or safety of TripAlong, our users, or the public</Li>
          <Li>Detect, prevent, or address fraud, security vulnerabilities, or technical issues</Li>
          <Li>Enforce our Terms of Service</Li>
        </ul>

        <Sub n="3.4" title="Business Transfers." />
        <P>
          If TripAlong is involved in a merger, acquisition, financing, reorganization, bankruptcy, or
          sale of all or a portion of our assets, your information may be transferred as part of that
          transaction. We will notify you (via email or in-app notice) before your information becomes
          subject to a different privacy policy.
        </P>

        <Sub n="3.5" title="With Your Explicit Consent." />
        <P>
          We may share your information with third parties for purposes not described in this Policy
          when we have your explicit consent to do so.
        </P>

        <Sub n="3.6" title="What We Do NOT Do." />
        <div className="my-4 rounded-2xl border p-4"
          style={{ background: 'rgba(48,209,88,0.05)', borderColor: 'rgba(48,209,88,0.2)' }}>
          <ul className="list-disc ml-4 space-y-2">
            <Li><strong className="text-white/85">We do not sell your personal information</strong> to third parties, data brokers, or advertisers</Li>
            <Li><strong className="text-white/85">We do not share your information with advertisers</strong> for targeted advertising</Li>
            <Li><strong className="text-white/85">We do not share your private messages</strong> except as required by law or as necessary to enforce our Terms</Li>
          </ul>
        </div>

        {/* ── 4 ── */}
        <S n="4" title="Data Retention" />
        <P>
          We retain your personal information for as long as your account is active or as needed to
          provide the Service to you.
        </P>
        <P>
          If you delete your account, we will delete or anonymize your personal information within{' '}
          <strong className="text-white">30 days</strong>, except where:
        </P>
        <ul className="list-disc ml-5 space-y-2 mb-4">
          <Li>We are required to retain it by applicable law (e.g., tax, financial records)</Li>
          <Li>Retention is necessary to resolve a pending dispute or enforce our agreements</Li>
          <Li>Retention is necessary for fraud prevention or safety investigations</Li>
        </ul>
        <P>
          Messages you sent in group chats may remain visible to other members after you delete your
          account, attributed to a deleted user. We may retain aggregate, anonymized data that cannot
          identify you indefinitely for analytics and research.
        </P>

        {/* ── 5 ── */}
        <S n="5" title="Security" />
        <P>
          We implement industry-standard technical, administrative, and physical security measures to
          protect your information, including:
        </P>
        <ul className="list-disc ml-5 space-y-2 mb-4">
          <Li>Encryption of data in transit using TLS/HTTPS</Li>
          <Li>Encryption of sensitive data at rest</Li>
          <Li>Password hashing using strong cryptographic algorithms (we never store plaintext passwords)</Li>
          <Li>Access controls limiting which employees and systems can access personal data</Li>
          <Li>Regular security reviews</Li>
        </ul>
        <P>
          <strong className="text-white">However, no method of transmission over the internet or
          electronic storage is 100% secure.</strong> We cannot guarantee absolute security of your
          information. You use the Service at your own risk and are responsible for maintaining the
          security of your own devices and account credentials.
        </P>
        <P>
          If you suspect your account has been compromised, contact us immediately at{' '}
          <a href="mailto:support@tripalong.app" className="underline" style={{ color: 'rgba(255,255,255,0.7)' }}>
            support@tripalong.app
          </a>.
        </P>
        <P>
          In the event of a data breach that affects your rights and freedoms, we will notify you and
          applicable authorities as required by law.
        </P>

        {/* ── 6 ── */}
        <S n="6" title="Your Privacy Rights" />
        <P>
          Depending on your location, you may have the following rights regarding your personal
          information. To exercise any of these rights, contact us at{' '}
          <a href="mailto:privacy@tripalong.app" className="underline" style={{ color: 'rgba(255,255,255,0.7)' }}>
            privacy@tripalong.app
          </a>{' '}
          with subject line &quot;Privacy Request.&quot; We will respond within{' '}
          <strong className="text-white">30 days</strong>.
        </P>

        <Sub n="6.1" title="Access." />
        <P>You may request a copy of the personal information we hold about you.</P>

        <Sub n="6.2" title="Correction." />
        <P>
          You may update or correct inaccurate personal information by editing your profile directly in
          the app, or by contacting us.
        </P>

        <Sub n="6.3" title="Deletion." />
        <P>
          You may request deletion of your account and personal data at any time via{' '}
          <strong className="text-white">Settings → Danger Zone → Delete Account</strong>, or by
          emailing{' '}
          <a href="mailto:privacy@tripalong.app" className="underline" style={{ color: 'rgba(255,255,255,0.7)' }}>
            privacy@tripalong.app
          </a>. We will delete your data within 30 days, subject to the exceptions in Section 4.
        </P>

        <Sub n="6.4" title="Data Portability." />
        <P>
          You may request a copy of your personal data in a structured, portable format by contacting
          us at{' '}
          <a href="mailto:privacy@tripalong.app" className="underline" style={{ color: 'rgba(255,255,255,0.7)' }}>
            privacy@tripalong.app
          </a>.
        </P>

        <Sub n="6.5" title="Opt-Out of Non-Essential Communications." />
        <P>
          You may opt out of push notifications and email updates by adjusting notification settings in
          the app. Note that we may still send you essential service-related communications (e.g.,
          account security alerts).
        </P>

        <Sub n="6.6" title="California Residents — CCPA/CPRA Rights." />
        <P>
          If you are a California resident, you have the following rights under the California Consumer
          Privacy Act (CCPA) and California Privacy Rights Act (CPRA):
        </P>
        <ul className="list-disc ml-5 space-y-2 mb-4">
          <Li><strong className="text-white/80">Right to Know:</strong> Know what personal information we collect, use, disclose, or sell about you</Li>
          <Li><strong className="text-white/80">Right to Delete:</strong> Request deletion of your personal information, subject to certain exceptions</Li>
          <Li><strong className="text-white/80">Right to Correct:</strong> Request correction of inaccurate personal information</Li>
          <Li><strong className="text-white/80">Right to Opt Out of Sale:</strong> We do not sell personal information, so this right is not applicable, but you can confirm this by contacting us</Li>
          <Li><strong className="text-white/80">Right to Non-Discrimination:</strong> We will not discriminate against you for exercising any of these rights</Li>
        </ul>
        <P>
          To submit a California privacy request, contact{' '}
          <a href="mailto:privacy@tripalong.app" className="underline" style={{ color: 'rgba(255,255,255,0.7)' }}>
            privacy@tripalong.app
          </a>. We may need to verify your identity before processing your request.
        </P>

        <Sub n="6.7" title="EEA, UK, and Swiss Residents — GDPR Rights." />
        <P>
          If you are located in the European Economic Area (EEA), United Kingdom, or Switzerland,
          you have the following rights under the General Data Protection Regulation (GDPR) or
          equivalent legislation:
        </P>
        <ul className="list-disc ml-5 space-y-2 mb-4">
          <Li><strong className="text-white/80">Right of Access</strong> to your personal data (Art. 15 GDPR)</Li>
          <Li><strong className="text-white/80">Right to Rectification</strong> of inaccurate data (Art. 16)</Li>
          <Li><strong className="text-white/80">Right to Erasure</strong> (&quot;right to be forgotten&quot;) (Art. 17)</Li>
          <Li><strong className="text-white/80">Right to Restriction</strong> of processing (Art. 18)</Li>
          <Li><strong className="text-white/80">Right to Data Portability</strong> (Art. 20)</Li>
          <Li><strong className="text-white/80">Right to Object</strong> to processing based on legitimate interests (Art. 21)</Li>
          <Li><strong className="text-white/80">Right not to be subject</strong> to solely automated decision-making (Art. 22)</Li>
        </ul>
        <P>
          <strong className="text-white">Legal Bases for Processing.</strong> We process your data on
          the following legal bases: (a) <strong className="text-white/80">Contract performance</strong> —
          to provide the Service you requested; (b) <strong className="text-white/80">Legitimate
          interests</strong> — for safety, fraud prevention, and service improvement; (c){' '}
          <strong className="text-white/80">Consent</strong> — for optional features like push
          notifications; (d) <strong className="text-white/80">Legal obligation</strong> — where
          required by law.
        </P>
        <P>
          You may lodge a complaint with your local supervisory data protection authority. In the EU,
          you can find your authority at edpb.europa.eu. We would, however, appreciate the chance to
          address your concerns first — please contact{' '}
          <a href="mailto:privacy@tripalong.app" className="underline" style={{ color: 'rgba(255,255,255,0.7)' }}>
            privacy@tripalong.app
          </a>.
        </P>

        {/* ── 7 ── */}
        <S n="7" title="Children's Privacy" />
        <div className="my-4 rounded-2xl border p-4"
          style={{ background: 'rgba(255,59,48,0.06)', borderColor: 'rgba(255,59,48,0.2)' }}>
          <P>
            <strong className="text-white">TripAlong is intended exclusively for users who are
            18 years of age or older.</strong> We do not knowingly collect personal information from
            anyone under the age of 18. Our Service is not directed at children.
          </P>
          <P>
            If we learn that we have collected personal information from a person under 18 without
            verifiable parental consent, we will delete that information as quickly as possible. If you
            believe we may have information from or about a person under 18, please contact us at{' '}
            <a href="mailto:legal@tripalong.app" className="underline" style={{ color: 'rgba(255,255,255,0.7)' }}>
              legal@tripalong.app
            </a>{' '}
            immediately.
          </P>
        </div>

        {/* ── 8 ── */}
        <S n="8" title="International Data Transfers" />
        <P>
          TripAlong is operated from the United States. If you access the Service from outside the
          United States, your information will be transferred to and processed in the United States,
          where data protection laws may differ from those in your home country.
        </P>
        <P>
          For transfers of personal data from the EEA, UK, or Switzerland to the United States, we
          rely on appropriate legal mechanisms such as the European Commission&apos;s Standard Contractual
          Clauses (SCCs) or other approved transfer mechanisms to ensure an adequate level of protection.
        </P>
        <P>
          By using the Service from outside the United States, you acknowledge that your information
          will be processed in the United States.
        </P>

        {/* ── 9 ── */}
        <S n="9" title="Cookies and Tracking Technologies" />
        <P>
          We use cookies and similar technologies (e.g., local storage, session tokens) to keep you
          logged into the Service, remember your preferences, and understand how users interact with
          the Service.
        </P>
        <InfoBox>
          <ul className="list-disc ml-4 space-y-1.5">
            <Li><strong className="text-white/80">Essential cookies:</strong> Required for the Service to function (authentication, session management). These cannot be disabled.</Li>
            <Li><strong className="text-white/80">Analytics cookies:</strong> Help us understand usage patterns to improve the Service. You may opt out via browser settings.</Li>
          </ul>
        </InfoBox>
        <P>
          We do not use third-party advertising cookies or sell data to ad networks. You can control
          cookie preferences through your browser settings, though disabling essential cookies will
          prevent the Service from functioning properly.
        </P>

        {/* ── 10 ── */}
        <S n="10" title="Third-Party Links and Services" />
        <P>
          The Service may contain links to or integrations with third-party websites and services
          (e.g., Google Maps, external booking sites). This Privacy Policy does not apply to those
          third parties. We encourage you to review the privacy policies of any third-party services
          you interact with. We are not responsible for the privacy practices of third parties.
        </P>

        {/* ── 11 ── */}
        <S n="11" title="Do Not Track" />
        <P>
          Some browsers have a &quot;Do Not Track&quot; (&quot;DNT&quot;) feature that signals to websites
          that you do not want your online activity tracked. Because there is no standard for how
          companies respond to DNT signals, we do not currently respond to DNT signals. We will
          reassess this position if an industry standard is adopted.
        </P>

        {/* ── 12 ── */}
        <S n="12" title="Changes to This Privacy Policy" />
        <P>
          We may update this Privacy Policy from time to time. When we do, we will update the
          &quot;Last Updated&quot; date at the top of this page. For material changes — changes that
          significantly affect how we use your information or your rights — we will notify you by
          posting a prominent notice in the app or sending an email to your registered address at
          least 30 days before the changes take effect.
        </P>
        <P>
          Your continued use of the Service after the effective date of the revised Privacy Policy
          constitutes your acceptance of the changes. If you do not agree to the revised Policy, you
          must stop using the Service and delete your account.
        </P>

        {/* ── 13 ── */}
        <S n="13" title="Contact Us" />
        <P>
          If you have questions, concerns, or requests regarding this Privacy Policy or your personal
          data, please contact us:
        </P>
        <div className="rounded-2xl p-5 mt-2" style={{ background: 'rgba(255,255,255,0.04)' }}>
          <p className="text-sm font-semibold text-white mb-1">TripAlong — Privacy Team</p>
          <p className="text-sm mb-1" style={{ color: 'rgba(255,255,255,0.55)' }}>
            Privacy requests:{' '}
            <a href="mailto:privacy@tripalong.app" className="underline" style={{ color: 'rgba(255,255,255,0.75)' }}>
              privacy@tripalong.app
            </a>
          </p>
          <p className="text-sm mb-1" style={{ color: 'rgba(255,255,255,0.55)' }}>
            Legal inquiries:{' '}
            <a href="mailto:legal@tripalong.app" className="underline" style={{ color: 'rgba(255,255,255,0.75)' }}>
              legal@tripalong.app
            </a>
          </p>
          <p className="text-sm" style={{ color: 'rgba(255,255,255,0.55)' }}>
            General support:{' '}
            <a href="mailto:support@tripalong.app" className="underline" style={{ color: 'rgba(255,255,255,0.75)' }}>
              support@tripalong.app
            </a>
          </p>
        </div>
        <P>
          We commit to responding to all privacy-related inquiries within{' '}
          <strong className="text-white">30 days</strong>. For urgent security concerns, please
          use the subject line &quot;URGENT — Privacy&quot; in your email.
        </P>

        {/* Footer */}
        <div className="flex items-center gap-5 mt-16 pt-8 border-t"
          style={{ borderColor: 'rgba(255,255,255,0.07)' }}>
          <Link href="/terms" className="text-xs" style={{ color: 'rgba(255,255,255,0.35)' }}>
            Terms of Service →
          </Link>
        </div>
      </main>
    </div>
  )
}
